[test] Git action test

diff --git a/.github/workflows/frontend-cd.yml b/.github/workflows/frontend-cd.yml
--- a/.github/workflows/frontend-cd.yml
+++ b/.github/workflows/frontend-cd.yml
@@ -46,7 +46,7 @@ jobs:
         with:
           name: dist-archive
           path: dist.tar.gz
-          
+
   # 빌드 성공하면
   deploy:
     needs: build
@@ -85,7 +85,18 @@ jobs:
         run: |
           scp -i ~/.ssh/deploy_key -P ${{ secrets.FRONT_PORT }} dist.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/ubuntu/renewal
 
-      # 압축 해제 후 nginx 검사 및 reload
+      # 압축 해제 후 압축 파일 삭제
       - name: Extract dist and reload nginx
         run: |
-          ssh -i ~/.ssh/deploy_key -p ${{ secrets.FRONT_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd /home/ubuntu/renewal && tar -xzf dist.tar.gz && rm -f dist.tar.gz && sudo nginx -t && sudo nginx -s reload"
+          ssh -i ~/.ssh/deploy_key -p ${{ secrets.FRONT_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
+          cd /home/ubuntu/renewal &&
+          tar -xzf dist.tar.gz &&
+          rm -f dist.tar.gz
+          "
+      - name: Verify deployment
+        run: |
+          STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://sku-sku.com)
+          if [ "$STATUS" != "200" ]; then
+            echo "Deployment failed with status $STATUS"
+            exit 1
+          fi
